CoureWork
danloncer/JavaOfDanya pull request #15
Opened 2021-10-08 18:26 UTC by danloncer

2021-10-10 08:48 UTC, DisterRU requested changes
Нужно много доработок.
В целом ок.

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/Employee.java
> +        }
Это лучше написать в сеттере, а затем вызвать сеттер в конструкторе.

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/Employee.java
> +        this.id = Employee.counter;
Совершенно не обязательно обращаться с counter через класс.
Можно просто написать id = counter++;

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/Employee.java
> +        counter++;
Можно объединить с прошлой строкой.
Написал в комментарии выше.

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/Employee.java
> +    }
А тут проверки нет.
Т.е. можно установить любое число.

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +    public void deleteMember (String firstName, String middleName, int id) {
Пользователь вряд ли знает id.
А даже если так, то ему не надо знать ФИО.
Т.е. по фамилии и имени и по id должны быть разные методы.
И у тебя внизу есть удаление по id.
Следовательно, в этом методе id лишний.

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        }
Сотрудник не найден?

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        }
Сотрудник не найден?

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        System.out.println("Отдел успешно изменен.");
А как он успешно изменен, если сотрудник не был найден?

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        System.out.println("Отдел успешно изменен.");
А как он успешно изменен, если сотрудник не был найден?

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +            for (Employee business : listBusiness) {
Плохие имена для переменных.
employee и employeeList были бы сильно лучше.

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +    }
Нужно найти сотрудников с мин/макс зп, а не число.

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        percent = (percent / 100) + 1;
Это не процент, а мультиплаер (множитель).
Не надо переменной с процентами переприсваивать какое-то странное значение.

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +            float a = business.getCash() * percent;
Что за переменная a? Как понять, что она в себе хранит?

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        float min = 99999999999f;
Можно использовать константу Float.MAX_VALUE

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        return min;
Возврат должен быть сотрудника с мин зп, а не числа.

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        return max;
Возврат должен быть сотрудника с макс зп, а не числа.

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        percent = (percent / 100) + 1;
Снова переприсваиваем переменной процент значение множителя.

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +                float a = business.getCash() * percent;
Снова a

2021-10-10 08:48 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +                System.out.println("Name: " + business.getFirstName() + " " + business.getMiddleName() + " Cash: " + business.getCash() + " Id: " + business.getId());
toString?

2021-10-11 14:49 UTC, DisterDE requested changes
Всё ещё есть место для доработок.
Внимательнее читай комментарии.

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/Employee.java
> +            throw new RuntimeException("Отдел не должен быть больше 5 и не меньше 0");
Раз ты начал работать с исключениями, то нужно работать с ними корректно.
Runtime Exception нам ни о чем не говорит.
Нужно выбрасывать не его, а IllegalArgumentException, так как у нас проблема именно в значении переданного аргумента.

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +    private static float MAX_VALUE = 99999999999F;
Эта переменная не имеет смысла, так как имеет альтернативу в виду Float.MAX_VALUE.
К тому же, если переменная пишется капсом, значит она должна быть константной, а эта переменная не является такой (нет модификатора final)

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +            for (Employee business : listBusiness) {
Всё ещё плохие имена переменных.

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +            if (business == null) {
Плохие имена переменных.

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +            if (business == null) {
Плохие имена.

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        float min = MAX_VALUE;
float min = Float.MAX_VALUE.

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +            }
Второй цикл не нужен.
Нужно в первом цикле работать с двумя переменными.
Первая -- мин зарплата.
Вторая -- сотрудник с мин зарплатой.
И результатом метода возвращать этого сотрудника.
Не печатать, а именно возвращать.

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        float max = -1;
float max = Float.MIN_VALUE

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        }
Та же история, что с прошлым методом.

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        for (Employee business : listBusiness) {
Имена

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/Employee.java
> +    private final String middleName;
middleName -- отчество.
А нам нужна фамилия, т.е. lastName

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +            System.out.print(i + 1 + "." + listBusiness[i].getFirstName() + " " + listBusiness[i].getMiddleName() + "\n");
Зачем тут print?
Почему не написать
`System.out.println(i + 1 + "." + listBusiness[i].getFirstName() + " " + listBusiness[i].getMiddleName())`
?

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +            business.setCash(business.getCash() * (percent/100+1));
Рассчитать множитель нужно перед циклом.
Считать его заново на каждом шаге не имеет смысла.

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        float min = MAX_VALUE;
float min = Float.MAX_VALUE

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +    }
Тот же комментарий, что был к поиску минимума и максимума у всех сотрудников.
Нужно в одном цикле работать с двумя переменными и возвращать сотрудника, а не печатать.

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +                business.setCash(business.getCash() * (percent/100+1));
Множитель вычислять вне цикла.
Чтобы не считать его каждый раз.

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +            if (business == null) {
Имена.

2021-10-11 14:49 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +                System.out.println("Зарплата выше порога: " + threshold + " : " + business.getFirstName() + " " + business.getMiddleName() + " :Cash: " + business.getCash() + " :Id: " + business.getI
А зачем каждый раз писать порог?
Ну сделай одну строку "Зарплата выше порога:" и потом в цикле выводи с новых строк сотрудников.

2021-10-11 14:49 UTC, DisterDE commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +    }
Тот же комментарий, что был к прошлому методу.

2021-10-14 18:51 UTC, DisterRU approved these changes
Уже лучше.
Осталось только заменить возврат строк на Employee и можно мержить.

2021-10-14 18:51 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/Employee.java
> +    private static int counter = 0;
Совершенно не требуется явно присваивать 0, так как это значение присвоится автоматически (дефолтное значение int является 0).

2021-10-14 18:51 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +    }
Нужно не строку возвращать, а объект Employee
Т.е. return listBusiness[salId]; (кстати, имя всё ещё плохое для массива)

2021-10-14 18:51 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +        int i = -1;
Делаем i = 1

2021-10-14 18:51 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +            i++;
Убираем.

2021-10-14 18:51 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +            System.out.println(i + 1 + "." + worker.getFirstName() + " " + worker.getlastName());
Заменяем на System.out.println(i++ + "." + worker.getFirstName() + " " + worker.getlastName());

2021-10-14 18:51 UTC, DisterRU commented on src/pro/sky/java/course1/CourseWork/EmployeeBook.java
> +    }
Тоже нужно возвращать объект Employee, т.е. return listBusiness[salId]

2021-10-14 20:09 UTC, merged